### ISSUE TITLE
Cannot create a `WEBSOCKET` check with `data`

### ISSUE THREAD

**Issue by StanAngeloff** [NodePing/nodeping-ansible#4]
I'm trying to create a `WEBSOCKET` check which sends some custom data to the web socket server. The `data` module arg is currently defined as `data=dict(type='dict', required=False)` which forces the use of a dictionary. However, [websocket_check](https://github.com/NodePing/python-nodeping-api/blob/1.0/nodeping_api/create_check.py#L1748) in the Python API expects a string.

How about aliasing `postdata` to `data` if a `checktype` of `WEBSOCKET` is used and no `data` argument is provided?

**Comment by NodePing** [comment]
The latest commit fixes this issue. To add data to the `data` field use the `websocketdata` arg. If you encounter anymore issues feel free to reopen this issue.

Thanks
